In [1]:
import numpy as np
from keras import layers
from keras.layers import Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from keras.models import Model, load_model
from keras.initializers import glorot_uniform
import matplotlib.pyplot as plt

In [3]:
noise= np.random.normal(0,1, [12, 100])

In [5]:
noise.shape

(12, 100)

In [8]:
from keras.datasets.mnist import load_data

In [9]:
# Load the dataset
(X_train, _), (_, _) = load_data()

In [10]:
# Rescale -1 to 1
X_train = (X_train.astype(np.float32) - 127.5) / 127.5

In [11]:
X_train.shape

(60000, 28, 28)

In [12]:
X_train1 = np.expand_dims(X_train, axis=3)

In [13]:
X_train1.shape

(60000, 28, 28, 1)

In [14]:
half_batch = 64
a = np.ones((half_batch, 1))

In [16]:
a.shape

(64, 1)

In [21]:
b = np.arange(10).reshape(10,1)

In [22]:
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [31]:
c = np.arange(9,-1,-1).reshape(10,1)

In [32]:
c

array([[9],
       [8],
       [7],
       [6],
       [5],
       [4],
       [3],
       [2],
       [1],
       [0]])

In [33]:
np.add(b,c)

array([[9],
       [9],
       [9],
       [9],
       [9],
       [9],
       [9],
       [9],
       [9],
       [9]])

In [37]:
batch_size = 128
valid_y =  np.array([1] * batch_size)

In [40]:
valid_y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
[1]*12

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]